version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Chicago
    versioning-strategy: increase-if-necessary
    groups:
      major:
        update-types:
          - major
      patches:
        update-types:
          - patch
    commit-message:
      prefix: chore
      include: scope
